#!/bin/sh
mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base2.repo_bak;
wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo;
yum makecache;
yum install wget;
yum install -y SDL gcc make perl;
yum install -y VirtualBox*.rpm;
yum insyall kernel-devel;
ver=$(uname -r)
if [ $ver != "3.10.0-862.14.4.el7.x86_64" ]; then  
      yum install -y https://github.com/SAddr/file/raw/master/kerneldevel514.rpm
else
      yum install -y kernel-devel kernel-devel-3.10.0-862.el7.x86_64
fi  
/sbin/vboxconfig
mv /etc/yum.repos.d/CentOS-Base2.repo_bak /etc/yum.repos.d/CentOS-Base.repo;
yum makecache
exit 0
