#!/bin/sh
mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base2.repo_bak;
wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo;
yum makecache;
yum install -y SDL gcc make perl;
yum install -y https://download.virtualbox.org/virtualbox/5.2.22/VirtualBox-5.2-5.2.22_126460_el7-1.x86_64.rpm;
ver=$(uname -r)
if [ $ver == "3.10.0-514.el7.x86_64" ]; then  
      yum install -y https://github.com/SAddr/file/raw/master/kerneldevel514.rpm
else
      yum install -y https://github.com/SAddr/file/raw/master/kernel-devel-3.10.0-862.el7.x86_64.rpm
fi  
yum insyall kernel-devel;
/sbin/vboxconfig
mv /etc/yum.repos.d/CentOS-Base2.repo_bak /etc/yum.repos.d/CentOS-Base.repo;
yum makecache
exit 0
